### PR TITLE
setting up organ gallery page

### PR DESCRIPTION
**Pull request by cqing5**

### CODE REVIEW

**Comment by bherr2** [comment]
@cqing5 Are you not able to test/develop locally? Seems like you are having trouble as this has taken almost 30 days now. Anything we can do to help?

**Comment by cqing5** [comment]
Hi Bruce, the reason why it's taken a while is largely due to trouble with the SVG file and continuous changes to the icon. Everything is done now though, so I will be creating a pull request soon after Andi confirms. Thank you for offering to help!
________________________________
From: Bruce W. Herr II ***@***.***>
Sent: Tuesday, July 19, 2022 12:38 PM
To: hubmapconsortium/ccf ***@***.***>
Cc: Qing, Catherine Y ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [hubmapconsortium/ccf] setting up organ gallery page (PR #22)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@cqing5<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcqing5&data=05%7C01%7Ccqing%40iu.edu%7C2159e05399cf4a43e97808da69a5350e%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637938455528925785%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5fnnF5irPPKUpbT0wLuqLzexngrhIdsaE%2Feqwki%2FpQo%3D&reserved=0> Are you not able to test/develop locally? Seems like you are having trouble as this has taken almost 30 days now. Anything we can do to help?

**Comment by cqing5** [comment]
finished ccf organ vr gallery page

**Comment by bherr2** [comment]
Links on subpages back to gallery fail (too many /pages/ in the URL)

**Comment by bherr2** [comment]
(basically for subpages remove the "pages/" part of the URL... Follow the model and you'll see)

**Comment by cqing5** [comment]
fixed it—thank you for catching that!
________________________________
From: Bruce W. Herr II ***@***.***>
Sent: Tuesday, July 19, 2022 1:18 PM
To: hubmapconsortium/ccf ***@***.***>
Cc: Qing, Catherine Y ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [hubmapconsortium/ccf] setting up organ gallery page (PR #22)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


(basically for subpages remove the "pages/" part of the URL... Follow the model and you'll see)

**Review by bherr2 — APPROVED** [review]

**Pull request merged**
